### PR TITLE
Change `TargetFrameworks` to netstandard2.0 and 4.0

### PR DESCRIPTION
**Pull request by ricaun**
### dotnet
- Change dotnet project to `Microsoft.NET.Sdk`
- Change `TargetFrameworks` to netstandard2.0 and 4.0
- Add `GeneratePackageOnBuild`
- Add `dotbim.jpg`

### test
- Change test project to `Microsoft.NET.Sdk`
- Change `TargetFramework` to net5.0

### CODE REVIEW

**Comment by paireks** [comment]
Hey Luiz!

Thank you for your input! :)
I tried to check it out, and:
- I can successfully build a project. Nugets has been restored and everything seems fine.
- But right now I cannot run the tests. All tests are marked as "Inconclusive". Are the tests running on your computer? Just for the record: I'm using Rider IDE, but if everything is set up properly - we both should be able to run the tests, no matter on which IDE :)

Let me know if you have any ideas how to fix the tests. Merry Christmas to you! :)

**Comment by ricaun** [comment]
Hello Wojciech! 

I'm using Visual Studio and the test project has some 'xunit.runner.visualstudio' package references, I supposed that could be the issue. I usually use NUnit to make tests and run these tests in GitHub action, xunit I never used 😢

I created a new branch with the test using NUnit, https://github.com/ricaun/dotbim/tree/nunit

Another thing I changed is the `Newtonsoft.Json` version to 9.* and in the current configuration the package is not gonna appear with dependencies, so the project can select any version. I work with Revit plugins and each Revit version has a specific `Newtonsoft.Json` version, that's the reason I changed so I know is gonna work in a plugin.

You should create a develop branch, usually is not a good idea to send directly to the master branch. 😉

And Merry Christmas! 🤘

**Comment by paireks** [comment]
Ok, regarding tests it turned out that they run well, the test coverage doesn't work, but during some research it seems to be an issue with dotCover itself most likely. I think I can merge it then as it is, but before that I'll probably create a new Nuget and see in other projects if everything seems fine after update. Will let you know :)

P.S. - If you have any comments regarding existing Nuget regarding what should be improved or changed - let me know, so maybe we can deal with it already :)

**Comment by ricaun** [comment]
* I update the 'Newtonsoft.Json' to appear in the dependencies, in this case gonna appear as `Newtonsoft.Json (>= 9.0.1)` in the https://www.nuget.org/packages/dotbim/#dependencies-body-tab
* I updated the nuget version to 1.0.1 in the csproj.

Everything should work fine, the main code was not changed, another thing that could be nice to add is the documentation file.
I added this line in the csproj. 
```xml
  <!-- Disable DocumentationFile
  <PropertyGroup Condition="!$(Configuration.Contains('Debug'))">
    <DocumentationFile>$(OutputPath)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>
  -->
```
If you enable all the public methods and classes gonna require documentation, if not implemented the compiler gonna show some warning.

**Comment by paireks** [comment]
Thanks for all input!
Once I will create new nuget and upload it, I will merge 1_0_1 with master :)

**Comment by ricaun** [comment]
Neat! 
Is possible to automate that as well, to run some GitHub action to generate the package, sign and send to the nuget. This action is trigger when something is marged with the master branch.
* https://github.com/ricaun-io/ricaun.Nuke
Just need to config some secrets and should work.

**Pull request merged**
